language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/account.json"
  global:
  - secure: Tl3N7lShuCpEbRD7utbqNLF842CDjPO/MNukdXuxXjMVoWzE9ECFCLJfRyvPD1L9WEUNBlTtunCb3nwwAPe7U4kVLpjcS5m/5R0UkJj5oAG3JlfFDlbOwn2PBKoT3MtmbWh8A7ZjFNby8p8yC6Eoe/FcyI6Av3XV+zD/3k5VH7Ykpp9VbWgOJJzVbP+t0djB7XsDtSsjKUVbGEjsH15yUIzGwkLvNKCiksj1sFOW3phGesgXgNzcn6MB7QMnn1MnP2Xky6gEamEV8ZpYxsZ3Ld8kv/RP/Yai2JGRRB0q0lPXVKyl+UwORhCxB/as7K0xX4cwCeWSEocYnTBIFPZHeeG+84hlDPKKtfc0sTKlisOU8q9eMzDBb7HpccdW8U/tUEIcCvB+3gWumaBmoD8a7trDcdk2+UwDT+vxPUk7fhKRfpMxbzVZbDWjJJwuFYsrYRMfhncMRDV3NbjH6/OqninGU2dOwrnthJP/zE2j322ePQcbqXeV0CjLM51bjgbghIawgqq/GN+qJ/bwDk3egGcrlN7kMYYLBSUzeumCm+K88qB2NUll2suv5lciinw6HRc4Y4L2WO3KAC6gnwOLUczBVV1suPrfm1qa31rm2OBaCmKDnjcvd9K2FixuoltXRVkIGieLWTlzwryBddyYQuyV8Pdq7g96FXC5tmR3NE4=
  - secure: UeBDvMRkMZ6fQG9FMFbnk5he38scaVZabUWIrJBIdXsJX2vUOzPh8agBDZVc3quEjxus4ufyiabgAFh6hT255/jSlC0kQq4WY6C4tLCVafZWwVmXVzoK8KNwNOG/6wlwFEVmcOugj1Qq46cTHoEXguYEqA7vkosJwgIWJvxS18+bj7xI2maMqcOlNjJcsaS+XwzFnT1vQBU45LymAkcPHEndmt/OIElAnED+9EVCqITfMfJGZ5ocBKhBGmQ0c8wC0bR4jV/5aWWYawZ+LcLBmOR4FImKKdUcCOnJoqmMRoXYfxD5OCE+snYg7SxkXIBoP4B1Zxd64pITfkaCrL0VkQhSs2ixkmqUxOTvfDDBnJvQZdfsAqy4HK+QKKtVmWXUiX0IOZV6AG3w4kzRd0wfEa+6vtLqRVwG9KIh14YqyBzHSGEw6uCPhBFk4PXcpSygMtynd2g5IdOmgOkk++RQpwfWIx2qfB7TZswHFUzU3zorr2sM6DG5As0D4p2n3SzO462XsIGGveLg8kXpyVnIpr/6fBLoPu/rqbIko9xAlcQKsO7Lrd5N2TbUwGXftkQ87sWiU0LNx4ZMcnN1RCppW7WvPD9GW4vlQPZ67pueFbOrDmV3bCnSmfZHKQ8K2pb9YkI5FM5h4iMcSwUmIeVmCIovMPA6G+oVhX+l5k7o2YI=
  - secure: rS9hCTzEMIta6wEmDpgL44JRjsBtmcgDv7SUfkSSBGKaFobfu63UZEVbHoPOYWMRjwccOhuMz04w8DGyNbhKObPLwpht1/L9pGyT00ZlOoP9l25VdDEMJGwhSMo+BPvyIn5dAwsKDXKeiiqBXbWItbN4lGUbwDR3GihOccAgVeR8eJbkZBsDWghrle0BUu3oMjxvJXqGhvahCZf2HAVgZ08goDfSK7+KAJe+kry9M8n0Qi/lJJGmV62p/KkjhxbyKgPqLE+E6RAeHnCWQX0u5iK4EzRrA+ILbVe0VfLTQ1h+mhy3O33IpQLEp78BH7cv5oW2RQFRGQxtaZVC3VWrgz1xCdCTqQrX9eVJvmBabaX08N2ggBh+VfYmF99OXxtcmG04cSAByZDDWHwsLrfXVKMT5OpVR7coUhtx1xmHSj8UIHQsVTrnAgSHeJ/NgKSIdV0WuF71YXVzuRXpM+vHpgoRzQUVIR4odaP2LXgy9l/5+ff3mMpoqyc6XbrwofFkDmy2jzxWd4PZF67F8OBwxrRhaacWUYv0cn6PndWgkiRLw89EZRU0/Fp4fTGDUQnk4IUc0+4rCLTeBAeDtnlURax7NI9elXw4tN43x9ngfPvvJtjJUYeRNHyqY5/Rcwm7Ta720eYrdhAu29nvCnE/6qdmjE3syEJWY0SnnyWNmcY=
script:
- molecule create
- molecule converge
- molecule verify
before_install:
- openssl aes-256-cbc -K $encrypted_063127390e3c_key -iv $encrypted_063127390e3c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
