---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: instanse
    zone: europe-west1-d
    machine_type: f1-micro
     
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
   - dependency
   - create
   - prepare
   - converge
   - converge
   - verify
   - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
